//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensaje
    {
        public int Id { get; set; }
        public Nullable<int> IdChat { get; set; }
        public string Mensaje1 { get; set; }
        public string Respuesta { get; set; }
        public Nullable<int> IdRemitente { get; set; }
    
        public virtual ChatProducto ChatProducto { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
